### ISSUE TITLE
Use iam-jdbc-driver in keycloak

### ISSUE THREAD

**Issue by jameshcovington** [magJ/iam-jdbc-driver#5]
Trying to use this driver in order to connect my keycloak container to AWS RDS Aurora postgresql with IAM authentication. So far I'm unable to get a driver recognized for the jdbc url "jdbc:iampostgresql"

**Comment by magJ** [comment]
Probably better off asking on keycloak support channels about how to load the driver. I took a brief look and ran into a couple of different issues.
They seem to have two different docker distributions, a wildfly(legacy) based image, and a quarkus based image.  

Keycloak have [some documentation](https://www.keycloak.org/docs/latest/server_installation/#packaging-the-jdbc-driver) on packaging jdbc drivers, but it seems like it's only relevant to their legacy wildfly based images.
I couldn't easily load the driver in the wildfly image, because the start script doesn't seem to support non-standard drivers.

I don't know a lot of about quarkus, but it seems like it might need some compile time configuration to load a given jdbc driver, I'm not sure how exactly to get it to work with that.
